[build]
  functions = "netlify/functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["sharp"]

[[edge_functions]]
  function = "share"
  path = "/share/*"
